### ISSUE TITLE
No aks version specified so example fails on deployment.yml

### ISSUE THREAD

**Issue by raboley** [MicrosoftDocs/pipelines-javascript-docker#13]
When following the example documentation for [azure environments deployments](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops) the `Deploy to Kubernetes cluster` step will fail on the error

> no matches for kind "Deployment" in version "apps/v1beta1"

which is due to the default aks version as of time of writing using kubernetes 1.16 which takes `Deployment` out of version `apps/v1beta1` and into `apps/v1`
kubernetes versions have been updated making the ./manifests/deployment.yml out of date. it currently

## Workaround

update the ./manifests/deployment.yml to reference apps/v1 instead of `apps/v1beta1` adn add a selector field that matches the template metatdata label. example:

```yaml
#./manifests/deployment.yml
apiVersion : apps/v1
kind: Deployment
metadata:
  name: raboleypipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raboleypipelinesjavascriptdocker 
  template:
    metadata:
      labels:
        app: raboleypipelinesjavascriptdocker 
    spec:
      containers:
        - name: raboleypipelinesjavascriptdocker 
          image: rabenvcr.azurecr.io/raboleypipelinesjavascriptdocker
          ports:
          - containerPort: 8080
```

## Fix 

Pin the version the kubernetes cluster will use, and then update the Deployment version to whatever works in that version.
